github: []
patreon: zhongshengzhishu
open_collective: zhongshengzhishu
ko_fi: zhongshengzhishu
tidelift: ""
community_bridge: ""
liberapay: zhongshengzhishu
otechie: ""
custom: ["https://qr.alipay.com/fkx123456789"]
